### ISSUE TITLE
Perm des E-Mail-Plugins nicht korrekt

### ISSUE THREAD

**Issue by akuehnis** [yakamara/yform#1501]
Bei der Version 4.2.1 des E-Mail-Plugins wurde eine falsche perm verbaut
package.yml

Version 4.2.0:
```
package: yform/email
version: '4.2.0'
author: 'Jan Kristinus'
supportpage: 'https://github.com/yakamara/yform/issues'

page:
    title: 'translate:yform_email_templates'
    perm: yform[email]
    pjax: true
    subpages:
        index: { title: 'translate:yform_email_templates', hidden: true }
```

Version 4.2.1 (falsch):
```
package: yform/email
version: '4.2.1'
license: MIT
author: 'Jan Kristinus'
supportpage: 'https://github.com/yakamara/yform/issues'

page:
    title: 'translate:yform_email_templates'
    perm: admin[]
    pjax: true
    subpages:
        index: { title: 'translate:yform_email_templates', hidden: true }
```

admin[] führt dazu dass der Zugriff nicht einer Rolle zugewiesen werden kann.
